name: Clean TestFlight Upload

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload to TestFlight
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Build Archive
      run: |
        cd sdl2/iOS
        
        echo "=== Building Archive ==="
        xcodebuild \
          -project np2sdl2.xcodeproj \
          -scheme np2sdl2 \
          -destination "generic/platform=iOS" \
          -configuration Release \
          -archivePath np2sdl2.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=12.0 \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=56M5TL55LH \
          PRODUCT_BUNDLE_IDENTIFIER=com.msonrm.np2-ios2 \
          archive
          
        echo "=== Archive Created ==="
        ls -la np2sdl2.xcarchive/
          
    - name: Export IPA  
      run: |
        cd sdl2/iOS
        
        # Create export options
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>56M5TL55LH</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>destination</key>
            <string>upload</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
        echo "=== Exporting IPA ==="
        xcodebuild \
          -exportArchive \
          -archivePath np2sdl2.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist
          
        echo "=== Export Complete ==="
        ls -la export/
        find export -name "*.ipa" -exec ls -la {} \;
        
    - name: Upload to TestFlight
      run: |
        cd sdl2/iOS
        
        IPA_FILE=$(find export -name "*.ipa" | head -1)
        echo "Found IPA: $IPA_FILE"
        
        echo "=== Uploading to TestFlight ==="
        xcrun altool --upload-app \
          --type ios \
          --file "$IPA_FILE" \
          --username "${{ secrets.APPLE_ID }}" \
          --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
          --verbose