name: Build IPA for TestFlight

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Build Archive (No Code Signing)
      run: |
        cd sdl2/iOS
        
        echo "=== Building without code signing ==="
        xcodebuild \
          -project np2sdl2.xcodeproj \
          -scheme np2sdl2 \
          -destination "generic/platform=iOS" \
          -configuration Release \
          -archivePath np2sdl2.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=12.0 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          archive
          
    - name: Upload Archive Artifact
      uses: actions/upload-artifact@v4
      with:
        name: np2-archive
        path: sdl2/iOS/np2sdl2.xcarchive
        retention-days: 7
        
    - name: Instructions
      run: |
        echo "============================================"
        echo "Archive created successfully!"
        echo "============================================"
        echo "To create IPA for TestFlight:"
        echo "1. Download the archive from GitHub Actions artifacts"
        echo "2. Open Xcode Organizer"
        echo "3. Import the archive"
        echo "4. Click 'Distribute App' -> 'App Store Connect'"
        echo "5. Follow the signing and upload process"
        echo "============================================"