name: Build and Upload to TestFlight

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Upload to TestFlight
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Install Certificate and Provisioning Profile
      env:
        PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: "actions"
      run: |
        # Create keychain
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
        # Import certificate (using existing file directly)
        security import certificates/ios_distribution_nopass.p12 -P "" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH -T /usr/bin/codesign -T /usr/bin/xcodebuild
        
        # Install provisioning profile
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode --output $PP_PATH
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
        
        # Verify setup
        security find-identity -v -p codesigning $KEYCHAIN_PATH
        
    - name: Build Archive
      run: |
        cd sdl2/iOS
        
        echo "=== Building with automatic signing ==="
        xcodebuild \
          -project np2sdl2.xcodeproj \
          -scheme np2sdl2 \
          -destination "generic/platform=iOS" \
          -configuration Release \
          -archivePath np2sdl2.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=12.0 \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }} \
          PRODUCT_BUNDLE_IDENTIFIER=com.msonrm.np2sdl2 \
          archive
          
    - name: Export IPA
      run: |
        cd sdl2/iOS
        
        # Create export options
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${{ secrets.APPLE_TEAM_ID }}</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>upload</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
        # Export IPA
        xcodebuild \
          -exportArchive \
          -archivePath np2sdl2.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist
          
    - name: Upload to TestFlight
      env:
        API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      run: |
        cd sdl2/iOS
        
        # Create App Store Connect API key file
        mkdir -p ~/private_keys
        echo "$API_PRIVATE_KEY" > ~/private_keys/AuthKey_$API_KEY_ID.p8
        
        # Upload to TestFlight using altool
        xcrun altool --upload-app \
          --type ios \
          --file export/*.ipa \
          --apiKey $API_KEY_ID \
          --apiIssuer $API_ISSUER_ID \
          --verbose
        
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: np2-ipa
        path: sdl2/iOS/export/*.ipa
        retention-days: 7