name: TestFlight Release

on:
  push:
    tags:
      - 'v*'  # バージョンタグ作成時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  build-and-deploy:
    name: Build and Deploy to TestFlight
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Setup App Store Connect API
      env:
        API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUE_ID }}
        API_PRIVATE_KEY: ${{ secrets.APPLE_API_KEY_BASE64 }}
      run: |
        mkdir -p ~/private_keys
        echo "$API_PRIVATE_KEY" | base64 --decode > ~/private_keys/AuthKey_$API_KEY_ID.p8
        chmod 600 ~/private_keys/AuthKey_$API_KEY_ID.p8
        
    - name: Build Archive
      env:
        API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUE_ID }}
      run: |
        cd sdl2/iOS
        
        echo "=== Building for TestFlight Distribution ==="
        xcodebuild \
          -project np2sdl2.xcodeproj \
          -scheme np2sdl2 \
          -destination "generic/platform=iOS" \
          -configuration Release \
          -archivePath np2sdl2.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=12.0 \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=56M5TL55LH \
          PRODUCT_BUNDLE_IDENTIFIER=com.msonrm.np2-ios2 \
          -allowProvisioningUpdates \
          -authenticationKeyPath ~/private_keys/AuthKey_$API_KEY_ID.p8 \
          -authenticationKeyID $API_KEY_ID \
          -authenticationKeyIssuerID $API_ISSUER_ID \
          archive
          
    - name: Create Export Options
      run: |
        cd sdl2/iOS
        
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>56M5TL55LH</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>upload</string>
            <key>signingStyle</key>
            <string>automatic</string>
        </dict>
        </plist>
        EOF
        
    - name: Debug Archive Contents
      run: |
        cd sdl2/iOS
        echo "=== Archive Contents ==="
        find np2sdl2.xcarchive -name "*.png" | head -20
        echo "=== App Bundle Icons ==="
        find np2sdl2.xcarchive -path "*/np2sdl2.app/*" -name "Icon*.png" -exec ls -la {} \;
        echo "=== Info.plist Icon References ==="
        /usr/libexec/PlistBuddy -c "Print CFBundleIconFiles" np2sdl2.xcarchive/Products/Applications/np2sdl2.app/Info.plist || true
        /usr/libexec/PlistBuddy -c "Print CFBundleIcons" np2sdl2.xcarchive/Products/Applications/np2sdl2.app/Info.plist || true
        
    - name: Export IPA
      env:
        API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUE_ID }}
      run: |
        cd sdl2/iOS
        
        echo "=== Exporting IPA ==="
        xcodebuild \
          -exportArchive \
          -archivePath np2sdl2.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist \
          -allowProvisioningUpdates \
          -authenticationKeyPath ~/private_keys/AuthKey_$API_KEY_ID.p8 \
          -authenticationKeyID $API_KEY_ID \
          -authenticationKeyIssuerID $API_ISSUER_ID
          
    - name: Upload to TestFlight
      env:
        API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUE_ID }}
      run: |
        cd sdl2/iOS
        
        echo "=== Uploading to TestFlight ==="
        xcrun altool --upload-app \
          --type ios \
          --file export/*.ipa \
          --apiKey $API_KEY_ID \
          --apiIssuer $API_ISSUER_ID \
          --verbose
          
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: np2-testflight-ipa
        path: sdl2/iOS/export/*.ipa
        retention-days: 7
        
    - name: Clean up
      if: always()
      run: |
        rm -rf ~/private_keys || true